apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: quarkus-demo-trigger
  name: el-quarkus-demo-trigger
spec:
  host: el-quarkus-demo-trigger-tay-test.apps.mbusa-dview.sd11.p1.openshiftapps.com
  port:
    targetPort: http-listener
  to:
    kind: Service
    name: el-quarkus-demo-trigger
    weight: 100
  wildcardPolicy: None
