---
apiVersion: tekton.dev/v1beta1
metadata:
  name: tay-pipeline
  namespace: tay-test
  labels:
    resource: pipeline
kind: Pipeline
spec:
  workspaces:
  - name: ssh-creds
  - name: shared-workspace
  params:
  - name: git-url
    type: string
    description: url of the git repo for the code of deployment
    default: git@github.com:Mint3kool/quarkus-demo.git
  - name: git-revision
    type: string
    description: revision to be used from repo of the code for deployment
    default: "main"
  - name: image_registry
    type: string
    description: image registry url
    default: quay.io/tshen
  - name: image_name
    type: string
    default: quarkus-demo
  - name: image_version
    type: string
    default: latest
  tasks:
  - name: fetch-source
    taskRef:
      name: git-clone
      kind: ClusterTask
    workspaces:
    - name: ssh-directory
      workspace: ssh-creds
    - name: output
      workspace: shared-workspace
    params:
    - name: url
      value: $(params.git-url)
    - name: subdirectory
      value: ""
    - name: deleteExisting
      value: "true"
    - name: revision
      value: $(params.git-revision)
  - name: build-code
    taskRef:
      name: update-dockerfile
    workspaces:
    - name: source
      workspace: shared-workspace
    runAfter:
    - fetch-source
  - name: build-image
    taskRef:
      name: buildah
      kind: ClusterTask
    workspaces:
    - name: source
      workspace: shared-workspace
    params:
    - name: IMAGE
      value: $(params.image_registry)/$(params.image_name):$(params.image_version)
#    - name: DOCKERFILE
#      value: quarkus-demo/src/main/docker/Dockerfile.legacy-jar
    runAfter:
    - build-code
