---
kind: Secret
apiVersion: v1
metadata:
  name: my-ssh-credentials
  namespace: tay-test
  labels:
    resource: pipeline
data:
  id_rsa: LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUFNd0FBQUF0emMyZ3RaVwpReU5UVXhPUUFBQUNCUkZuTGZ2WHVvak9tRndNUEEyazloZFBMczJmSTRkckpYRFZZaGVQMnNEZ0FBQUppZUVEMUpuaEE5ClNRQUFBQXR6YzJndFpXUXlOVFV4T1FBQUFDQlJGbkxmdlh1b2pPbUZ3TVBBMms5aGRQTHMyZkk0ZHJKWERWWWhlUDJzRGcKQUFBRUF1N2ovci9ka2ZCa2RFWFh0OUEycThmdk95Tmg2UUdIS2ZMNHptMEtteVAxRVdjdCs5ZTZpTTZZWEF3OERhVDJGMAo4dXpaOGpoMnNsY05WaUY0L2F3T0FBQUFEblJoZVVCeVpXUm9ZWFF1WTI5dEFRSURCQVVHQnc9PQotLS0tLUVORCBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0K
