apiVersion: v1
kind: PersistentVolume
metadata:
  name: pipeline-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  nfs:
    path: /tmp
    server: 172.17.0.2
  storageClassName: slow
