apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  labels:
    resource: pipeline
    tekton.dev/pipeline: test-pipelinerun
  generateName: test-pipelinerun-
spec:
  params:
  - name: git-url
    value: git@github.com:Mint3kool/quarkus-demo.git
  - name: git-revision
    value: main
  - name: IMAGE
    value: tay-image
  pipelineRef:
    name: test-pipeline
  serviceAccountName: pipeline
  timeout: 1h0m0s
  workspaces:
  - name: ssh-creds
    secret:
      secretName: my-ssh-credentials
  - name: shared-workspace
    persistentVolumeClaim:
      claimName: pipeline-pvc
